name: Build PDF Manual

on:
  workflow_dispatch:
  workflow_call: # Required for orchestration

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: manual.tex

      - name: Prepare Pages folder
        run: |
          mkdir -p _site
          cp -r web/* _site/
          cp manual.pdf _site/

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
