name: Combined Build Release and Build PDF Manual

on:
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build-documentation:
    uses: ./.github/workflows/build-pdf-manual.yml
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets: inherit

  build-executable:
    needs: build-documentation
    uses: ./.github/workflows/build-release.yml
    permissions:
      contents: write
      packages: write
      actions: write
    secrets: inherit
